
function TemplateInit(){
  let TemInit = [
    {
      "alias": 'education',
      "col_name": 'education',
      "data": "{\"name\":\"select\",\"title\":\"下拉单选\",\"desc\":\"单选，需要指定数据源\",\"template\":\"<el-select :allow-create=\\\"false\\\" filterable style=\\\"width: 100%;\\\" :disabled=\\\"readonly\\\" clearable v-model=\\\"$${model}\\\"><el-option  v-for=\\\"item in $${alias}_option_data\\\" :key=\\\"item.pk\\\" :label=\\\"item.$${name_field}\\\" :value=\\\"item.$${value_field}\\\"></el-option></el-select>\",\"needDataSource\":true,\"data_source\":\"{\\n  \\\"url\\\": \\\"parameters\\\",\\n  \\\"params\\\": {\\n    \\\"category\\\": \\\"学历\\\"\\n  },\\n  \\\"name_field\\\": \\\"name\\\",\\n  \\\"value_field\\\": \\\"name\\\"\\n}\"}",
      "local_data_source": "{\n  \"url\": \"parameters\",\n  \"params\": {\n    \"category\": \"学历\"\n  },\n  \"name_field\": \"name\",\n  \"value_field\": \"name\"\n}",
      'col_title': "学历",
      'in_filter': false,
      'is_related': false,
      'is_required': true,
      'is_vant_show': false,
      'unique': false,
      'verify_exp': "[]",
      'widget': 'select',
      'widget_attr': '[]'
    },
    {
      "alias": 'academic_degree',
      "col_name": 'academic_degree',
      "local_data_source": "{\n  \"url\": \"parameters\",\n  \"params\": {\n    \"category\": \"学位\"\n  },\n  \"name_field\": \"name\",\n  \"value_field\": \"name\"\n}",
      "data": "{\"name\":\"select\",\"title\":\"下拉单选\",\"desc\":\"单选，需要指定数据源\",\"template\":\"<el-select :allow-create=\\\"false\\\" filterable style=\\\"width: 100%;\\\" :disabled=\\\"readonly\\\" clearable v-model=\\\"$${model}\\\"><el-option  v-for=\\\"item in $${alias}_option_data\\\" :key=\\\"item.pk\\\" :label=\\\"item.$${name_field}\\\" :value=\\\"item.$${value_field}\\\"></el-option></el-select>\",\"needDataSource\":true,\"data_source\":\"{\\n  \\\"url\\\": \\\"parameters\\\",\\n  \\\"params\\\": {\\n    \\\"category\\\": \\\"学位\\\"\\n  },\\n  \\\"name_field\\\": \\\"name\\\",\\n  \\\"value_field\\\": \\\"name\\\"\\n}\"}",
      'col_title': "学位",
      'in_filter': false,
      'is_related': false,
      'is_required': true,
      'is_vant_show': false,
      'unique': false,
      'verify_exp': "[]",
      'widget': 'select',
      'widget_attr': '[]'
    },
    {
      "alias": 'job_time',
      "col_name": 'datetime_01',
      'col_title': "参加工作时间",
      "local_data_source": null,
      "data": null,
      'in_filter': false,
      'is_related': false,
      'is_required': true,
      'is_vant_show': false,
      'unique': false,
      'verify_exp': "[]",
      'widget': 'date',
      'widget_attr': '[]'
    },
    {
      "alias": 'inauguration_date',
      "col_name": 'inauguration_date',
      'col_title': "入职时间",
      "local_data_source": null,
      "data": null,
      'in_filter': false,
      'is_related': false,
      'is_required': true,
      'is_vant_show': false,
      'unique': false,
      'verify_exp': "[]",
      'widget': 'date',
      'widget_attr': '[]'
    },
    {
      "alias": 'job_position',
      "col_name": 'job_position',
      'col_title': "职务",
      "local_data_source": null,
      "data": null,
      'in_filter': false,
      'is_related': false,
      'is_required': true,
      'is_vant_show': false,
      'unique': false,
      'verify_exp': "[]",
      'widget': 'input',
      'widget_attr': '[]'
    },
    {
      "alias": 'profession',
      "col_name": 'profession',
      'col_title': "职称",
      "local_data_source": null,
      "data": null,
      'in_filter': false,
      'is_related': false,
      'is_required': true,
      'is_vant_show': false,
      'unique': false,
      'verify_exp': "[]",
      'widget': 'input',
      'widget_attr': '[]'
    },
    {
      "alias": 'job_post',
      "col_name": 'job_post',
      'col_title': "岗位",
      "local_data_source": null,
      "data": null,
      'in_filter': false,
      'is_related': false,
      'is_required': true,
      'is_vant_show': false,
      'unique': false,
      'verify_exp': "[]",
      'widget': 'input',
      'widget_attr': '[]'
    },
    {
      "alias": 'zhaunru_date',
      "col_name": 'effective_start_date',
      'col_title': "转入本岗日期",
      "local_data_source": null,
      "data": null,
      'in_filter': false,
      'is_related': false,
      'is_required': true,
      'is_vant_show': false,
      'unique': false,
      'verify_exp': "[]",
      'widget': 'date',
      'widget_attr': '[]'
    },
    {
      "alias": 'lizhi_date',
      "col_name": 'effective_end_date',
      'col_title': "离职时间",
      "local_data_source": null,
      "data": null,
      'in_filter': false,
      'is_related': false,
      'is_required': true,
      'is_vant_show': false,
      'unique': false,
      'verify_exp': "[]",
      'widget': 'date',
      'widget_attr': '[]'
    },
    {
      "alias": 'tuixiu_date',
      "col_name": 'datetime_02',
      'col_title': "退休时间",
      "local_data_source": null,
      "data": null,
      'in_filter': false,
      'is_related': false,
      'is_required': true,
      'is_vant_show': false,
      'unique': false,
      'verify_exp': "[]",
      'widget': 'date',
      'widget_attr': '[]'
    },
    {
      "alias": 'chenghao',
      "col_name": 'json_01',
      'col_title': "获得称号",
      "local_data_source": null,
      "data": null,
      'in_filter': false,
      'is_related': false,
      'is_required': true,
      'is_vant_show': false,
      'unique': false,
      'verify_exp': "[]",
      'widget': 'input',
      'widget_attr': '[]'
    },
    {
      "alias": 'remark',
      "col_name": 'remark',
      'col_title': "备注",
      "local_data_source": null,
      "data": null,
      'in_filter': false,
      'is_related': false,
      'is_required': true,
      'is_vant_show': false,
      'unique': false,
      'verify_exp': "[]",
      'widget': 'input',
      'widget_attr': '[]'
    },
    {
      "alias": 'user_id',
      "col_name": 'user',
      'col_title': "用户id",
      "local_data_source": null,
      "data": null,
      'in_filter': true,
      'is_related': false,
      'is_required': true,
      'is_vant_show': false,
      'unique': false,
      'verify_exp': "[]",
      'widget': 'input',
      'widget_attr': '[]'
    },
    {
      "alias": 'zhengshu',
      "col_name": 'field_03',
      'col_title': "证书",
      "local_data_source": null,
      "data": null,
      'in_filter': false,
      'is_related': false,
      'is_required': true,
      'is_vant_show': false,
      'unique': false,
      'verify_exp': "[]",
      'widget': 'file',
      'widget_attr': '[]'
    },
    {
      "alias": 'majors',
      "col_name": 'majors',
      'col_title': "专业",
      "local_data_source": null,
      "data": null,
      'in_filter': false,
      'is_related': false,
      'is_required': true,
      'is_vant_show': false,
      'unique': false,
      'verify_exp': "[]",
      'widget': 'input',
      'widget_attr': '[]'
    },
    {
      "alias": 'job_number',
      "col_name": 'field_01',
      'col_title': "工号",
      "local_data_source": null,
      "data": null,
      'in_filter': true,
      'is_related': false,
      'is_required': true,
      'is_vant_show': false,
      'unique': false,
      'verify_exp': "[\"required\"]",
      'widget': 'input',
      'widget_attr': "[\"clearable\"]"
    },
    {
      "alias": 'name',
      "col_name": 'name',
      'col_title': "姓名",
      "local_data_source": null,
      "data": null,
      'in_filter': true,
      'is_related': false,
      'is_required': true,
      'is_vant_show': false,
      'unique': false,
      'verify_exp': "[\"required\"]",
      'widget': 'input',
      'widget_attr': "[\"clearable\"]"
    },
    {
      "alias": 'gender',
      "col_name": 'gender',
      'col_title': "性别",
      "local_data_source": null,
      "data": null,
      'in_filter': true,
      'is_related': false,
      'is_required': true,
      'is_vant_show': false,
      'unique': false,
      'verify_exp': "[]",
      'widget': 'input',
      'widget_attr': "[\"clearable\"]"
    },
    {
      "alias": 'certificate_number',
      "col_name": 'certificate_number',
      'col_title': "身份证号",
      "local_data_source": null,
      "data": null,
      'in_filter': false,
      'is_related': false,
      'is_required': true,
      'is_vant_show': false,
      'unique': false,
      'verify_exp': "[\"idCard\"]",
      'widget': 'input',
      'widget_attr': "[]"
    },
    {
      "alias": 'birthday',
      "col_name": 'birthday',
      'col_title': "出生日期",
      "local_data_source": null,
      "data": null,
      'in_filter': false,
      'is_related': false,
      'is_required': true,
      'is_vant_show': false,
      'unique': false,
      'verify_exp': "[]",
      'widget': 'date',
      'widget_attr': "[]"
    },
    {
      "alias": 'graduated_college',
      "col_name": 'graduated_college',
      'col_title': "毕业院校",
      "local_data_source": null,
      "data": null,
      'in_filter': false,
      'is_related': false,
      'is_required': true,
      'is_vant_show': false,
      'unique': false,
      'verify_exp': "[]",
      'widget': 'input',
      'widget_attr': "[]"
    },
    {
      "alias": 'graduation_date',
      "col_name": 'graduation_date',
      'col_title': "毕业时间",
      "local_data_source": null,
      "data": null,
      'in_filter': false,
      'is_related': false,
      'is_required': true,
      'is_vant_show': false,
      'unique': false,
      'verify_exp': "[]",
      'widget': 'date',
      'widget_attr': "[]"
    }
  ]
  return TemInit
}
export default TemplateInit;
