
function TreeInit(){
  let TreeInit = [
    {
      "pk": null,
      "sys_id": null,
      "project": null,
      "parent": null,
      "children": [],
      "path": "/home",
      "title": "系统首页",
      "name": "home",
      "component": "home",
      "redirect": "/dashboard",
      "props": true,
      "alias": null,
      "meta": null
    },
    {
      "pk": null,
      "sys_id": null,
      "project": null,
      "parent": null,
      "children": [
        {
          "pk": null,
          "sys_id": null,
          "project": null,
          "parent": null,
          "children": [],
          "path": "/dashboard",
          "title": "系统首页",
          "name": "dashboard",
          "component": "dashboard",
          "redirect": "",
          "props": true,
          "alias": null,
          "meta": null
        },
        {
          "pk": null,
          "sys_id": null,
          "project": null,
          "parent": null,
          "children": [
            {
              "pk": null,
              "sys_id": null,
              "project": null,
              "parent": null,
              "children": [],
              "path": "ZhiGongGuanLi",
              "title": "职工管理",
              "name": "ZhiGongGuanLi",
              "component": "ZhiGongGuanLi",
              "redirect": "",
              "props": true,
              "alias": null,
              "meta": null
            },
            {
              "pk": null,
              "sys_id": null,
              "project": null,
              "parent": null,
              "children": [],
              "path": "JueSeGuanLi",
              "title": "系统管理",
              "name": "JueSeGuanLi",
              "component": "JueSeGuanLi",
              "redirect": "",
              "props": true,
              "alias": null,
              "meta": null
            },
            {
              "pk": null,
              "sys_id": null,
              "project": null,
              "parent": null,
              "children": [],
              "path": "FuWuXieYi",
              "title": "服务协议和隐私政策",
              "name": "FuWuXieYi",
              "component": "FuWuXieYi",
              "redirect": "",
              "props": true,
              "alias": null,
              "meta": null
            },
            {
              "pk": null,
              "sys_id": null,
              "project": null,
              "parent": null,
              "children": [],
              "path": "SystemLog",
              "title": "操作日志查询",
              "name": "SystemLog",
              "component": "SystemLog",
              "redirect": "",
              "props": true,
              "alias": null,
              "meta": null
            },
            {
              "pk": null,
              "sys_id": null,
              "project": null,
              "parent": null,
              "children": [],
              "path": "SystemLoginLog",
              "title": "登录日志查询",
              "name": "SystemLoginLog",
              "component": "SystemLoginLog",
              "redirect": "",
              "props": true,
              "alias": null,
              "meta": null
            }
          ],
          "path": "/system",
          "title": "系统管理",
          "name": "system",
          "component": "pageContainer",
          "redirect": "",
          "props": true,
          "alias": null,
          "meta": null
        }
      ],
      "path": "/",
      "title": "",
      "name": "main",
      "component": "home",
      "redirect": "/dashboard",
      "props": true,
      "alias": null,
      "meta": null
    },
    {
      "pk": null,
      "sys_id": null,
      "project": null,
      "parent": null,
      "children": [],
      "path": "/login",
      "title": "登录",
      "name": "login",
      "component": "login",
      "redirect": "",
      "props": true,
      "alias": null,
      "meta": null
    },
    {
      "pk": null,
      "sys_id": null,
      "project": null,
      "parent": null,
      "children": [],
      "path": "/ServicePrivacy",
      "title": "服务协议和隐私政策",
      "name": "ServicePrivacy",
      "component": "ServicePrivacy",
      "redirect": "",
      "props": true,
      "alias": null,
      "meta": null
    },
    {
      "pk": null,
      "sys_id": null,
      "project": null,
      "parent": null,
      "children": [],
      "path": "/changepassword",
      "title": "修改密码",
      "name": "changepassword",
      "component": "changepassword",
      "redirect": "",
      "props": true,
      "alias": null,
      "meta": null
    },
    {
      "pk": null,
      "sys_id": null,
      "project": null,
      "parent": null,
      "children": [],
      "path": "/smlogin",
      "title": "扫码登录",
      "name": "smlogin",
      "component": "smlogin",
      "redirect": "",
      "props": true,
      "alias": null,
      "meta": null
    },
    {
      "pk": null,
      "sys_id": null,
      "project": null,
      "parent": null,
      "children": [],
      "path": "/registerSuccess",
      "title": "注册页面",
      "name": "registerSuccess",
      "component": "registerSuccess",
      "redirect": "",
      "props": true,
      "alias": null,
      "meta": null
    },
    {
      "pk": null,
      "sys_id": null,
      "project": null,
      "parent": null,
      "children": [],
      "path": "/404",
      "title": "404",
      "name": "nn",
      "component": "notFound",
      "redirect": "",
      "props": false,
      "alias": null,
      "meta": null
    },
    {
      "pk": null,
      "sys_id": null,
      "project": null,
      "parent": null,
      "children": [],
      "path": "*",
      "title": "404",
      "name": "notFound",
      "component": "",
      "redirect": "/404",
      "props": false,
      "alias": null,
      "meta": null
    }
  ]
  return TreeInit
}
export default TreeInit;
