export default {
  customer: [
    {type: 0, value: "obj_id", label: "关联数据ID varchar(32)", is_show: true, idx: true},
    {type: 0,value: "user", label: "用户ID", is_show: true, idx: true},
    {type: 0,value: "department", label: "部门ID", is_show: true, idx: true,},
    {type: 0,value: "create_time", label: "创建时间timestamp with timezone", is_show: true, idx: false,},

    {type: 1,value: "gender", label: "性别varchar(2)", is_show: true, idx: false},
    {type: 1,value: "name", label: "姓名varchar(32)", is_show: true, idx: false},
    {type: 1,value: "qq", label: "QQvarchar(32)", is_show: true, idx: false},
    {type: 1,value: "phone_01", label: "联系电话1varchar(32)", is_show: true, idx: false,},
    {type: 1,value: "phone_02", label: "联系电话2varchar(32)", is_show: true, idx: false,},
    {type: 1,value: "emergency_contact", label: "紧急联系人varchar(32)", is_show: true, idx: false,},
    {type: 1,value: "emergency_phone", label: "紧急联系电话varchar(32)", is_show: true, idx: false,},
    {type: 1,value: "nick_name", label: "昵称varchar(31)", is_show: true, idx: false},
    {type: 1,value: "job_position", label: "职位varchar(32)", is_show: true, idx: false},
    {type: 1,value: "job_post", label: "岗位varchar(32)", is_show: true, idx: false},

    {type: 2,value: "en_name", label: "英文名varchar(64)", is_show: true, idx: false},
    {type: 2,value: "old_name", label: "曾用名varchar(64)", is_show: true, idx: false},
    {type: 2,value: "country", label: "国籍varchar(64)", is_show: true, idx: false},
    {type: 2,value: "nation", label: "民族varchar(64)", is_show: true, idx: false},
    {type: 2,value: "marital_status", label: "婚姻状况", is_show: true, idx: false,},
    {type: 2,value: "political_status", label: "政治面貌varchar(64)", is_show: true, idx: false,},
    {type: 2,value: "certificate_type", label: "证件类型varchar(64)", is_show: true, idx: false,},
    {type: 2,value: "certificate_number", label: "证件号码varchar(64)", is_show: true, idx: false,},
    {type: 2,value: "issuing_authority", label: "发证机关varchar(64)", is_show: true, idx: false,},

    {type: 3,value: "sn", label: "编号varchar(256)", is_show: true, idx: true},
    {type: 3,value: "gps_sn", label: "定位设备编号varchar(256)", is_show: true, idx: false,},
    {type: 3,value: "birthplace", label: "出生地varchar(256)", is_show: true, idx: false,},
    {type: 3,value: "hometown", label: "籍贯varchar(256)", is_show: true, idx: false},
    {type: 3,value: "mail", label: "邮箱varchar(255)", is_show: true, idx: false},
    {type: 3,value: "graduated_college", label: "毕业院校varchar(256)", is_show: true, idx: false,},
    {type: 3,value: "education", label: "学历varchar(256)", is_show: true, idx: false},
    {type: 3,value: "academic_degree", label: "学位varchar(256)", is_show: true, idx: false,},
    {type: 3,value: "majors", label: "专业varchar(256)", is_show: true, idx: false},
    {type: 3,value: "class_name", label: "班级varchar(256)", is_show: true, idx: false},
    {type: 3,value: "profession", label: "职业varchar(256)", is_show: true, idx: false},
    {type: 3,value: "qualification_name", label: "资格证书varchar(256)", is_show: true, idx: false,},
    {type: 3,value: "qualification_number", label: "资格证书编号varchar(256)", is_show: true, idx: false,},
    {type: 3,value: "qualification_level", label: "资格证书等级varchar(256)", is_show: true, idx: false,},
    {type: 3,value: "qualification_source", label: "资格证书发证机构varchar(256)", is_show: true, idx: false,},
    {type: 3,value: "work_place", label: "工作单位varchar(255)", is_show: true, idx: false,},

    {type: 4,value: "birthday", label: "出生日期date", is_show: true, idx: false},
    {type: 4,value: "death_date", label: "死亡日期date", is_show: true, idx: false},
    {type: 4,value: "end_date", label: "有效期截止日date", is_show: true, idx: false},
    {type: 4,value: "inauguration_date", label: "入职时间date", is_show: true, idx: false,},
    {type: 4,value: "effective_start_date", label: "有效开始日期date", is_show: true, idx: false,},
    {type: 4,value: "effective_end_date", label: "有效结束日期date", is_show: true, idx: false,},
    {type: 4,value: "enrollment_date", label: "入学日期date", is_show: true, idx: false},
    {type: 4,value: "graduation_date", label: "毕业日期date", is_show: true, idx: false},

    {type: 5,value: "datetime_01", label: "timestamp with timezone", is_show: true, idx: true,},
    {type: 5,value: "datetime_02", label: "timestamp with timezone", is_show: true, idx: true,},
    {type: 5,value: "update_time", label: "修改时间timestamp with timezone", is_show: true, idx: false,},

    {type: 6,value: "field_01", label: "varchar(1023)", is_show: true, idx: true},
    {type: 6,value: "field_02", label: "varchar(1023)", is_show: true, idx: true},
    {type: 6,value: "field_03", label: "varchar(1023)", is_show: true, idx: false,},
    {type: 6,value: "field_04", label: "varchar(1023)", is_show: true, idx: false,},
    {type: 6,value: "field_05", label: "varchar(1023)", is_show: true, idx: false,},
    {type: 6,value: "field_06", label: "varchar(1023)", is_show: true, idx: false,},
    {type: 6,value: "field_07", label: "varchar(1023)", is_show: true, idx: false,},
    {type: 6,value: "field_08", label: "varchar(1023)", is_show: true, idx: false,},
    {type: 6,value: "field_09", label: "varchar(1023)", is_show: true, idx: false,},
    {type: 6,value: "field_10", label: "varchar(1023)", is_show: true, idx: false,},

    {type: 7,value: "int_01", label: "bigint", is_show: true, idx: true},
    {type: 7,value: "int_02", label: "bigint", is_show: true, idx: true},
    {type: 7,value: "int_03", label: "bigint", is_show: true, idx: false},
    {type: 7,value: "int_04", label: "bigint", is_show: true, idx: false},
    {type: 7,value: "int_05", label: "bigint", is_show: true, idx: false},

    {type: 8,value: "address", label: "住址text", is_show: true, idx: false},
    {type: 8,value: "remark", label: "备注text", is_show: true, idx: false},
    {type: 8,value: "job_content", label: "工作内容text", is_show: true, idx: false},
    {type: 8,value: "id_photo", label: "证件照片text", is_show: true, idx: false},
    {type: 8,value: "photo", label: "本人照片text", is_show: true, idx: false},
    {type: 8,value: "qrcode", label: "二维码text", is_show: true, idx: false},
    {type: 8,value: "text_01", label: "text", is_show: true, idx: false},
    {type: 8,value: "json_01", label: "text", is_show: true, idx: false},
  ],
  formdata: [
    {type: 0, value: "user", label: "用户ID", is_show: true, idx: true,},
    {type: 0, value: "department", label: "部门ID", is_show: true, idx: true,},
    {type: 0, value: "obj_id", label: "关联数据ID", is_show: true, idx: false},
    {type: 0, value: "parent", label: "父级formdataID", is_show: true, idx: true,},
    {type: 0, value: "create_time", label: "创建时间timestamp with timezone", is_show: true, idx: false,},

    {type: 1, value: "longitude", label: "经度float", is_show: true, idx: true},
    {type: 1, value: "latitude", label: "纬度float", is_show: true, idx: true},
    {type: 1, value: "altitude", label: "海拔float", is_show: true, idx: true},

    {type: 2, value: "field_01", label: "varchar(1023)", is_show: true, idx: true},
    {type: 2, value: "field_02", label: "varchar(1023)", is_show: true, idx: true},
    {type: 2, value: "field_03", label: "varchar(1023)", is_show: true, idx: true},
    {type: 2, value: "field_04", label: "varchar(1023)", is_show: true, idx: true},
    {type: 2, value: "field_05", label: "varchar(1023)", is_show: true, idx: true},
    {type: 2, value: "field_06", label: "varchar(1023)", is_show: true, idx: false,},
    {type: 2, value: "field_07", label: "varchar(1023)", is_show: true, idx: false,},
    {type: 2, value: "field_08", label: "varchar(1023)", is_show: true, idx: false,},
    {type: 2, value: "field_09", label: "varchar(1023)", is_show: true, idx: false,},
    {type: 2, value: "field_10", label: "varchar(1023)", is_show: true, idx: false,},
    {type: 2, value: "field_11", label: "varchar(1023)", is_show: true, idx: false,},
    {type: 2, value: "field_12", label: "varchar(1023)", is_show: true, idx: false,},
    {type: 2, value: "field_13", label: "varchar(1023)", is_show: true, idx: false,},
    {type: 2, value: "field_14", label: "varchar(1023)", is_show: true, idx: false,},
    {type: 2, value: "field_15", label: "varchar(1023)", is_show: true, idx: false,},
    {type: 2, value: "field_16", label: "varchar(1023)", is_show: true, idx: false,},
    {type: 2, value: "field_17", label: "varchar(1023)", is_show: true, idx: false,},
    {type: 2, value: "field_18", label: "varchar(1023)", is_show: true, idx: false,},
    {type: 2, value: "field_19", label: "varchar(1023)", is_show: true, idx: false,},
    {type: 2, value: "field_20", label: "varchar(1023)", is_show: true, idx: false,},
    {type: 2, value: "field_21", label: "varchar(1023)", is_show: true, idx: false,},
    {type: 2, value: "field_22", label: "varchar(1023)", is_show: true, idx: false,},
    {type: 2, value: "field_23", label: "varchar(1023)", is_show: true, idx: false,},
    {type: 2, value: "field_24", label: "varchar(1023)", is_show: true, idx: false,},
    {type: 2, value: "field_25", label: "varchar(1023)", is_show: true, idx: false,},
    {type: 2, value: "field_26", label: "varchar(1023)", is_show: true, idx: false,},
    {type: 2, value: "field_27", label: "varchar(1023)", is_show: true, idx: false,},
    {type: 2, value: "field_28", label: "varchar(1023)", is_show: true, idx: false,},
    {type: 2, value: "field_29", label: "varchar(1023)", is_show: true, idx: false,},
    {type: 2, value: "field_30", label: "varchar(1023)", is_show: true, idx: false,},
    {type: 2, value: "field_31", label: "varchar(1023)", is_show: true, idx: false,},
    {type: 2, value: "field_32", label: "varchar(1023)", is_show: true, idx: false,},
    {type: 2, value: "field_33", label: "varchar(1023)", is_show: true, idx: false,},
    {type: 2, value: "field_34", label: "varchar(1023)", is_show: true, idx: false,},
    {type: 2, value: "field_35", label: "varchar(1023)", is_show: true, idx: false,},
    {type: 2, value: "field_36", label: "varchar(1023)", is_show: true, idx: false,},
    {type: 2, value: "field_37", label: "varchar(1023)", is_show: true, idx: false,},
    {type: 2, value: "field_38", label: "varchar(1023)", is_show: true, idx: false,},
    {type: 2, value: "field_39", label: "varchar(1023)", is_show: true, idx: false,},
    {type: 2, value: "field_40", label: "varchar(1023)", is_show: true, idx: false,},
    {type: 2, value: "field_41", label: "varchar(1023)", is_show: true, idx: false,},
    {type: 2, value: "field_42", label: "varchar(1023)", is_show: true, idx: false,},
    {type: 2, value: "field_43", label: "varchar(1023)", is_show: true, idx: false,},
    {type: 2, value: "field_44", label: "varchar(1023)", is_show: true, idx: false,},
    {type: 2, value: "field_45", label: "varchar(1023)", is_show: true, idx: false,},
    {type: 2, value: "field_46", label: "varchar(1023)", is_show: true, idx: false,},
    {type: 2, value: "field_47", label: "varchar(1023)", is_show: true, idx: false,},
    {type: 2, value: "field_48", label: "varchar(1023)", is_show: true, idx: false,},
    {type: 2, value: "field_49", label: "varchar(1023)", is_show: true, idx: false,},
    {type: 2, value: "field_50", label: "varchar(1023)", is_show: true, idx: false,},

    {type: 3, value: "date_01", label: "date", is_show: true, idx: true},
    {type: 3, value: "date_02", label: "date", is_show: true, idx: true},
    {type: 3, value: "date_03", label: "date", is_show: true, idx: true},
    {type: 3, value: "date_04", label: "date", is_show: true, idx: true},
    {type: 3, value: "date_05", label: "date", is_show: true, idx: true},
    {type: 3, value: "date_06", label: "date", is_show: true, idx: false},
    {type: 3, value: "date_07", label: "date", is_show: true, idx: false},
    {type: 3, value: "date_08", label: "date", is_show: true, idx: false},
    {type: 3, value: "date_09", label: "date", is_show: true, idx: false},
    {type: 3, value: "date_10", label: "date", is_show: true, idx: false},

    {type: 4, value: "datetime_01", label: "timestamp with timezone", is_show: true, idx: true,},
    {type: 4, value: "datetime_02", label: "timestamp with timezone", is_show: true, idx: true,},
    {type: 4, value: "datetime_03", label: "timestamp with timezone", is_show: true, idx: true,},
    {type: 4, value: "datetime_04", label: "timestamp with timezone", is_show: true, idx: true,},
    {type: 4, value: "datetime_05", label: "timestamp with timezone", is_show: true, idx: true,},
    {type: 4, value: "datetime_06", label: "timestamp with timezone", is_show: true, idx: false,},
    {type: 4, value: "datetime_07", label: "timestamp with timezone", is_show: true, idx: false,},
    {type: 4, value: "datetime_08", label: "timestamp with timezone", is_show: true, idx: false,},
    {type: 4, value: "datetime_09", label: "timestamp with timezone", is_show: true, idx: false,},
    {type: 4, value: "datetime_10", label: "timestamp with timezone", is_show: true, idx: false,},

    {type: 5, value: "int_01", label: "bigint", is_show: true, idx: true},
    {type: 5, value: "int_02", label: "bigint", is_show: true, idx: true},
    {type: 5, value: "int_03", label: "bigint", is_show: true, idx: false},
    {type: 5, value: "int_04", label: "bigint", is_show: true, idx: false},
    {type: 5, value: "int_05", label: "bigint", is_show: true, idx: false},
    {type: 5, value: "int_06", label: "bigint", is_show: true, idx: false},
    {type: 5, value: "int_07", label: "bigint", is_show: true, idx: false},
    {type: 5, value: "int_08", label: "bigint", is_show: true, idx: false},
    {type: 5, value: "int_09", label: "bigint", is_show: true, idx: false},
    {type: 5, value: "int_10", label: "bigint", is_show: true, idx: false},
    {type: 5, value: "int_11", label: "bigint", is_show: true, idx: true},
    {type: 5, value: "int_12", label: "bigint", is_show: true, idx: true},
    {type: 5, value: "int_13", label: "bigint", is_show: true, idx: false},
    {type: 5, value: "int_14", label: "bigint", is_show: true, idx: false},
    {type: 5, value: "int_15", label: "bigint", is_show: true, idx: false},
    {type: 5, value: "int_16", label: "bigint", is_show: true, idx: false},
    {type: 5, value: "int_17", label: "bigint", is_show: true, idx: false},
    {type: 5, value: "int_18", label: "bigint", is_show: true, idx: false},
    {type: 5, value: "int_19", label: "bigint", is_show: true, idx: false},
    {type: 5, value: "int_20", label: "bigint", is_show: true, idx: false},

    {type: 6, value: "float_01", label: "numeric(16,4)", is_show: true, idx: true},
    {type: 6, value: "float_02", label: "numeric(16,4)", is_show: true, idx: true},
    {type: 6, value: "float_03", label: "numeric(16,4)", is_show: true, idx: false,},
    {type: 6, value: "float_04", label: "numeric(16,4)", is_show: true, idx: false,},
    {type: 6, value: "float_05", label: "numeric(16,4)", is_show: true, idx: false,},
    {type: 6, value: "float_06", label: "numeric(16,4)", is_show: true, idx: false,},
    {type: 6, value: "float_07", label: "numeric(16,4)", is_show: true, idx: false,},
    {type: 6, value: "float_08", label: "numeric(16,4)", is_show: true, idx: false,},
    {type: 6, value: "float_09", label: "numeric(16,4)", is_show: true, idx: false,},
    {type: 6, value: "float_10", label: "numeric(16,4)", is_show: true, idx: false,},

    {type: 7, value: "text_01", label: "text", is_show: true, idx: false},
  ],
  goods: [
    {type: 0, value: "obj_id", label: "关联数据ID varchar(32)", is_show: true, idx: true},
    {type: 0, value: "id", label: "id", is_show: true, idx: false},
    {type: 0, value: "user", label: "用户ID", is_show: true, idx: true},
    {type: 0, value: "sys_id", label: "系统ID", is_show: true, idx: true},
    {type: 0, value: "org_id", label: "组织ID", is_show: true, idx: true},
    {type: 0, value: "biz_id", label: "业务ID", is_show: true, idx: true},
    {type: 0, value: "src_id", label: "数据源ID", is_show: true, idx: true},
    {type: 0, value: "own_org", label: "组织机构ID", is_show: true, idx: true},
    {type: 0, value: "department", label: "部门ID", is_show: true, idx: true,},
    {type: 0, value: "parent", label: "父级ID必须是本表ID varchar(32)", is_show: true, idx: true},
    {type: 0, value: "create_time", label: "timestamp with timezone", is_show: true, idx: false,},

    {type: 1, value: "color", label: "颜色 varchar(32)", is_show: true, idx: false},
    {type: 1, value: "number", label: "数量 varchar(32)", is_show: true, idx: false},

    {type: 2, value: "volume", label: "体积varchar(64)", is_show: true, idx: false},
    {type: 2, value: "long", label: "长varchar(64)", is_show: true, idx: false},
    {type: 2, value: "wide", label: "宽varchar(64)", is_show: true, idx: false},
    {type: 2, value: "high", label: "高varchar(64)", is_show: true, idx: false},
    {type: 2, value: "country", label: "进出口国家varchar(64)", is_show: true, idx: false,},
    {type: 2, value: "customs", label: "海关varchar(64)", is_show: true, idx: false},
    {type: 2, value: "province", label: "省varchar(64)", is_show: true, idx: true},
    {type: 2, value: "city", label: "市varchar(64)", is_show: true, idx: true},
    {type: 2, value: "region", label: "区varchar(64)", is_show: true, idx: true},
    {type: 2, value: "room", label: "房间varchar(64)", is_show: true, idx: false},
    {type: 2, value: "location", label: "位置varchar(64)", is_show: true, idx: false},
    {type: 2, value: "validity", label: "有效期varchar(64)", is_show: true, idx: false},

    {type: 3, value: "status", label: "状态varchar(128)", is_show: true, idx: false},
    {type: 3, value: "category", label: "类别varchar(128)", is_show: true, idx: true},
    {type: 3, value: "material", label: "材质varchar(128)", is_show: true, idx: false},
    {type: 3, value: "package", label: "包装varchar(128)", is_show: true, idx: false},
    {type: 3, value: "quality", label: "质量varchar(128)", is_show: true, idx: false},
    {type: 3, value: "township", label: "乡镇街道varchar(128)", is_show: true, idx: true},

    {type: 4, value: "name", label: "名称varchar(256)", is_show: true, idx: false},
    {type: 4, value: "sn", label: "编号varchar(256)", is_show: true, idx: false},
    {type: 4, value: "gps_sn", label: "定位设备编号varchar(256)", is_show: true, idx: false,},
    {type: 4, value: "brand", label: "品牌varchar(256)", is_show: true, idx: false},
    {type: 4, value: "size", label: "规格varchar(256)", is_show: true, idx: false},
    {type: 4, value: "model_num", label: "型号varchar(256)", is_show: true, idx: false},
    {type: 4, value: "address", label: "地址varchar(256)", is_show: true, idx: false},

    {type: 5, value: "float_01", label: "numeric(16,4)", is_show: true, idx: true},
    {type: 5, value: "float_02", label: "numeric(16,4)", is_show: true, idx: true},
    {type: 5, value: "float_03", label: "numeric(16,4)", is_show: true, idx: false,},
    {type: 5, value: "float_04", label: "numeric(16,4)", is_show: true, idx: false,},
    {type: 5, value: "float_05", label: "numeric(16,4)", is_show: true, idx: false,},
    {type: 5, value: "cost_01", label: "成本1numeric(16,4)", is_show: true, idx: false},
    {type: 5, value: "cost_02", label: "成本2numeric(16,4)", is_show: true, idx: false},
    {type: 5, value: "cost_03", label: "成本3numeric(16,4)", is_show: true, idx: false},
    {type: 5, value: "price_01", label: "价格1numeric(16,4)", is_show: true, idx: false},
    {type: 5, value: "price_02", label: "价格2numeric(16,4)", is_show: true, idx: false},
    {type: 5, value: "price_03", label: "成本3numeric(16,4)", is_show: true, idx: false},

    {type: 6, value: "latitude", label: "纬度float", is_show: true, idx: false},
    {type: 6, value: "longitude", label: "经度float", is_show: true, idx: false},
    {type: 6, value: "altitude", label: "海拔float", is_show: true, idx: false},

    {type: 7, value: "produced_time", label: "生产日期date", is_show: true, idx: false},
    {type: 7, value: "release_time", label: "发布日期date", is_show: true, idx: false},
    {type: 7, value: "added_time", label: "上架日期date", is_show: true, idx: false},
    {type: 7, value: "down_time", label: "下架日期date", is_show: true, idx: false},
    {type: 7, value: "import_time", label: "进口日期date", is_show: true, idx: false},
    {type: 7, value: "export_time", label: "出口日期date", is_show: true, idx: false},

    {type: 8, value: "update_time", label: "timestamp with timezone", is_show: true, idx: false,},
    {type: 8, value: "datetime_01", label: "timestamp with timezone", is_show: true, idx: true,},
    {type: 8, value: "datetime_02", label: "timestamp with timezone", is_show: true, idx: true,},
    {type: 8, value: "datetime_03", label: "timestamp with timezone", is_show: true, idx: false,},
    {type: 8, value: "datetime_04", label: "timestamp with timezone", is_show: true, idx: false,},
    {type: 8, value: "datetime_05", label: "timestamp with timezone", is_show: true, idx: false,},

    {type: 9, value: "field_01", label: "varchar(1023)", is_show: true, idx: true},
    {type: 9, value: "field_02", label: "varchar(1023)", is_show: true, idx: true},
    {type: 9, value: "field_03", label: "varchar(1023)", is_show: true, idx: true},
    {type: 9, value: "field_04", label: "varchar(1023)", is_show: true, idx: true},
    {type: 9, value: "field_05", label: "varchar(1023)", is_show: true, idx: true},
    {type: 9, value: "field_06", label: "varchar(1023)", is_show: true, idx: false,},
    {type: 9, value: "field_07", label: "varchar(1023)", is_show: true, idx: false,},
    {type: 9, value: "field_08", label: "varchar(1023)", is_show: true, idx: false,},
    {type: 9, value: "field_09", label: "varchar(1023)", is_show: true, idx: false,},
    {type: 9, value: "field_10", label: "varchar(1023)", is_show: true, idx: false,},

    {type: 10, value: "int_01", label: "bigint", is_show: true, idx: true},
    {type: 10, value: "int_02", label: "bigint", is_show: true, idx: true},
    {type: 10, value: "int_03", label: "bigint", is_show: true, idx: false},
    {type: 10, value: "int_04", label: "bigint", is_show: true, idx: false},
    {type: 10, value: "int_05", label: "bigint", is_show: true, idx: false},

    {type: 11, value: "product_description", label: "产品说明text", is_show: true, idx: false,},
    {type: 11, value: "barcode", label: "条形码text", is_show: true, idx: false},
    {type: 11, value: "qrcode", label: "二维码text", is_show: true, idx: false},
    {type: 11, value: "photo", label: "物品图片text", is_show: true, idx: false},
    {type: 11, value: "text_01", label: "text", is_show: true, idx: false},

  ],
  org: [
    {type: 0, value: "id", label: "id", is_show: true, idx: false},
    {type: 0, value: "user", label: "用户ID", is_show: true, idx: true},
    {type: 0, value: "sys_id", label: "系统ID", is_show: true, idx: true},
    {type: 0, value: "org_id", label: "组织ID", is_show: true, idx: true},
    {type: 0, value: "biz_id", label: "业务ID", is_show: true, idx: true},
    {type: 0, value: "src_id", label: "数据源ID", is_show: true, idx: true},
    {type: 0, value: "desc_article", label: "介绍 ArticleID", is_show: true, idx: true},
    {type: 0, value: "department", label: "部门 DepartmentID", is_show: true, idx: true,},
    {type: 0, value: "create_time", label: "timestamp with timezone", is_show: true, idx: false,},
    {type: 0, value: "obj_id", label: "关联数据ID", is_show: true, idx: true},

    {type: 1, value: "industry", label: "行业varchar(32)", is_show: true, idx: false},
    {type: 1, value: "phone", label: "联系电话varchar(32)", is_show: true, idx: false},
    {type: 1, value: "size", label: "规模varchar(32)", is_show: true, idx: false},
    {type: 1, value: "postcode", label: "邮编varchar(32)", is_show: true, idx: false},
    {type: 1, value: "lp_name", label: "法人varchar(32)", is_show: true, idx: false},
    {type: 1, value: "lp_id_type", label: "法人证件类型varchar(32)", is_show: true, idx: false,},
    {type: 1, value: "lp_id_number", label: "法人证件号码varchar(32)", is_show: true, idx: false,},
    {type: 1, value: "lp_phone", label: "法人联系电话varchar(32)", is_show: true, idx: false,},
    {type: 1, value: "contact_name", label: "联系人varchar(32)", is_show: true, idx: false,},
    {type: 1, value: "contact_phone", label: "联系人联系电话varchar(32)", is_show: true, idx: false,},
    {type: 1, value: "registered_capital", label: "注册资本varchar(32)", is_show: true, idx: false,},

    {type: 2, value: "org_type", label: "类型varchar(128)", is_show: true, idx: false},
    {type: 2, value: "org_number", label: "机构代码varchar(128)", is_show: true, idx: false,},
    {type: 2, value: "id_number", label: "证照编号varchar(128)", is_show: true, idx: false,},
    {type: 2, value: "ie_code", label: "进出口代码varchar(128)", is_show: true, idx: false,},
    {type: 2, value: "org_status", label: "状态varchar(128)", is_show: true, idx: false},
    {type: 2, value: "start_org", label: "举办单位varchar(128)", is_show: true, idx: false,},
    {type: 2, value: "main_org", label: "主管单位varchar(128)", is_show: true, idx: false,},
    {type: 2, value: "registration_org", label: "登记机关varchar(128)", is_show: true, idx: false,},

    {type: 3, value: "mail", label: "邮箱varchar(255)", is_show: true, idx: false},
    {type: 3, value: "lp_mail", label: "法人邮箱varchar(255)", is_show: true, idx: false},
    {type: 3, value: "contact_mail", label: "联系人邮箱varchar(255)", is_show: true, idx: false,},
    {type: 3, value: "name", label: "名称varchar(256)", is_show: true, idx: false},
    {type: 3, value: "en_name", label: "英文名varchar(256)", is_show: true, idx: false},
    {type: 3, value: "old_name", label: "曾用名varchar(256)", is_show: true, idx: false},
    {type: 3, value: "local", label: "所属地varchar(256)", is_show: true, idx: false},
    {type: 3, value: "link", label: "网址varchar(256)", is_show: true, idx: false},
    {type: 3, value: "address", label: "地址varchar(512)", is_show: true, idx: false},

    {type: 4, value: "longitude", label: "经度float", is_show: true, idx: false},
    {type: 4, value: "latitude", label: "纬度float", is_show: true, idx: false},
    {type: 4, value: "altitude", label: "海拔float", is_show: true, idx: false},

    {type: 5, value: "start_date", label: "成立时间date", is_show: true, idx: false},
    {type: 5, value: "end_date", label: "有效期限date", is_show: true, idx: false},
    {type: 5, value: "registration_date", label: "登记日期date", is_show: true, idx: false,},

    {type: 6, value: "update_time", label: "timestamp with timezone", is_show: true, idx: false,},

    {type: 7, value: "field_01", label: "varchar(1023)", is_show: true, idx: true},
    {type: 7, value: "field_02", label: "varchar(1023)", is_show: true, idx: true},
    {type: 7, value: "field_03", label: "varchar(1023)", is_show: true, idx: false,},
    {type: 7, value: "field_04", label: "varchar(1023)", is_show: true, idx: false,},
    {type: 7, value: "field_05", label: "varchar(1023)", is_show: true, idx: false,},
    {type: 7, value: "field_06", label: "varchar(1023)", is_show: true, idx: false,},
    {type: 7, value: "field_07", label: "varchar(1023)", is_show: true, idx: false,},
    {type: 7, value: "field_08", label: "varchar(1023)", is_show: true, idx: false,},
    {type: 7, value: "field_09", label: "varchar(1023)", is_show: true, idx: false,},
    {type: 7, value: "field_10", label: "varchar(1023)", is_show: true, idx: false,},
    {type: 7, value: "field_11", label: "varchar(1023)", is_show: true, idx: false,},
    {type: 7, value: "field_12", label: "varchar(1023)", is_show: true, idx: false,},
    {type: 7, value: "field_13", label: "varchar(1023)", is_show: true, idx: false,},
    {type: 7, value: "field_14", label: "varchar(1023)", is_show: true, idx: false,},
    {type: 7, value: "field_15", label: "varchar(1023)", is_show: true, idx: false,},
    {type: 7, value: "field_16", label: "varchar(1023)", is_show: true, idx: false,},
    {type: 7, value: "field_17", label: "varchar(1023)", is_show: true, idx: false,},
    {type: 7, value: "field_18", label: "varchar(1023)", is_show: true, idx: false,},
    {type: 7, value: "field_19", label: "varchar(1023)", is_show: true, idx: false,},
    {type: 7, value: "field_20", label: "varchar(1023)", is_show: true, idx: false,},
    {type: 7, value: "field_21", label: "varchar(1023)", is_show: true, idx: false,},
    {type: 7, value: "field_22", label: "varchar(1023)", is_show: true, idx: false,},
    {type: 7, value: "field_23", label: "varchar(1023)", is_show: true, idx: false,},
    {type: 7, value: "field_24", label: "varchar(1023)", is_show: true, idx: false,},
    {type: 7, value: "field_25", label: "varchar(1023)", is_show: true, idx: false,},
    {type: 7, value: "field_26", label: "varchar(1023)", is_show: true, idx: false,},
    {type: 7, value: "field_27", label: "varchar(1023)", is_show: true, idx: false,},
    {type: 7, value: "field_28", label: "varchar(1023)", is_show: true, idx: false,},
    {type: 7, value: "field_29", label: "varchar(1023)", is_show: true, idx: false,},
    {type: 7, value: "field_30", label: "varchar(1023)", is_show: true, idx: false,},
    {type: 7, value: "field_31", label: "varchar(1023)", is_show: true, idx: false,},
    {type: 7, value: "field_32", label: "varchar(1023)", is_show: true, idx: false,},
    {type: 7, value: "field_33", label: "varchar(1023)", is_show: true, idx: false,},
    {type: 7, value: "field_34", label: "varchar(1023)", is_show: true, idx: false,},
    {type: 7, value: "field_35", label: "varchar(1023)", is_show: true, idx: false,},
    {type: 7, value: "field_36", label: "varchar(1023)", is_show: true, idx: false,},
    {type: 7, value: "field_37", label: "varchar(1023)", is_show: true, idx: false,},
    {type: 7, value: "field_38", label: "varchar(1023)", is_show: true, idx: false,},
    {type: 7, value: "field_39", label: "varchar(1023)", is_show: true, idx: false,},
    {type: 7, value: "field_40", label: "varchar(1023)", is_show: true, idx: false,},
    {type: 7, value: "field_41", label: "varchar(1023)", is_show: true, idx: false,},
    {type: 7, value: "field_42", label: "varchar(1023)", is_show: true, idx: false,},
    {type: 7, value: "field_43", label: "varchar(1023)", is_show: true, idx: false,},
    {type: 7, value: "field_44", label: "varchar(1023)", is_show: true, idx: false,},
    {type: 7, value: "field_45", label: "varchar(1023)", is_show: true, idx: false,},
    {type: 7, value: "field_46", label: "varchar(1023)", is_show: true, idx: false,},
    {type: 7, value: "field_47", label: "varchar(1023)", is_show: true, idx: false,},
    {type: 7, value: "field_48", label: "varchar(1023)", is_show: true, idx: false,},
    {type: 7, value: "field_49", label: "varchar(1023)", is_show: true, idx: false,},
    {type: 7, value: "field_50", label: "varchar(1023)", is_show: true, idx: false,},

    {type: 8, value: "desc", label: "简介text", is_show: true, idx: false},
    {type: 8, value: "business_scope", label: "业务范围text", is_show: true, idx: false},
    {type: 8, value: "photo", label: "公司照片text", is_show: true, idx: false},
    {type: 8, value: "qrcode", label: "二维码text", is_show: true, idx: false},
    {type: 8, value: "field_01_display", label: "text", is_show: true, idx: false,},
    {type: 8, value: "field_02_display", label: "text", is_show: true, idx: false,},
    {type: 8, value: "field_03_display", label: "text", is_show: true, idx: false,},
    {type: 8, value: "field_04_display", label: "text", is_show: true, idx: false,},
    {type: 8, value: "field_05_display", label: "text", is_show: true, idx: false,},
    {type: 8, value: "field_06_display", label: "text", is_show: true, idx: false,},
    {type: 8, value: "field_07_display", label: "text", is_show: true, idx: false,},
    {type: 8, value: "field_08_display", label: "text", is_show: true, idx: false,},
    {type: 8, value: "field_09_display", label: "text", is_show: true, idx: false,},
    {type: 8, value: "field_10_display", label: "text", is_show: true, idx: false,},
    {type: 8, value: "text_01", label: "text", is_show: true, idx: false},
    {type: 8, value: "text_02", label: "text", is_show: true, idx: false},
    {type: 8, value: "text_03", label: "text", is_show: true, idx: false},
    {type: 8, value: "text_04", label: "text", is_show: true, idx: false},
    {type: 8, value: "text_05", label: "text", is_show: true, idx: false},
  ],
  services: [
    {type: 0, value: "create_user", label: "创建人 UserID", is_show: true, idx: true,},
    {type: 0, value: "user", label: "用户ID", is_show: true, idx: true},
    {type: 0, value: "obj_id", label: "关联数据ID", is_show: true, idx: true,},
    {type: 0, value: "department", label: "部门 DepartmentID", is_show: true, idx: true,},
    {type: 0, value: "create_time", label: "创建时间timestamp with timezone", is_show: true, idx: true,},
    {type: 0, value: "customera", label: "甲方 CustomerID", is_show: true, idx: true,},
    {type: 0, value: "customerb", label: "乙方 CustomerID", is_show: true, idx: true,},
    {type: 0, value: "customerc", label: "丙方 CustomerID", is_show: true, idx: true,},
    {type: 0, value: "usera", label: "甲方 UserID", is_show: true, idx: true,},
    {type: 0, value: "userb", label: "乙方 UserID", is_show: true, idx: true,},
    {type: 0, value: "userc", label: "丙方 UserID", is_show: true, idx: true,},
    {type: 0, value: "orga", label: "甲方组织机构 OrgID", is_show: true, idx: true,},
    {type: 0, value: "orgb", label: "乙方组织机构 OrgID", is_show: true, idx: true,},
    {type: 0, value: "orgc", label: "丙方组织机构 OrgID", is_show: true, idx: true,},
    {type: 0, value: "article", label: "内容链接 Article ID", is_show: true, idx: true,},

    {type: 1, value: "a_persion", label: "甲方联系人varchar(32)", is_show: true, idx: false},
    {type: 1, value: "b_persion", label: "乙方联系人varchar(32)", is_show: true, idx: false},
    {type: 1, value: "c_persion", label: "丙方联系人varchar(32)", is_show: true, idx: false},
    {type: 1, value: "a_phone", label: "甲方联系电话varchar(32)", is_show: true, idx: false},
    {type: 1, value: "b_phone", label: "乙方联系电话varchar(32)", is_show: true, idx: false},
    {type: 1, value: "c_phone", label: "丙方联系电话varchar(32)", is_show: true, idx: false},
    {type: 1, value: "deadline", label: "服务期限varchar(32)", is_show: true, idx: false},

    {type: 2, value: "audit_status", label: "审计或验收阶段状态varchar(64)", is_show: true, idx: false},
    {type: 2, value: "design_status", label: "设计阶段状态varchar(64)", is_show: true, idx: false},
    {type: 2, value: "construction_status", label: "施工阶段状态varchar(64)", is_show: true, idx: false},

    {type: 3, value: "sn", label: "服务编号varchar(256)", is_show: true, idx: true},
    {type: 3, value: "contract_sn", label: "合同编号varchar(256)", is_show: true, idx: true},
    {type: 3, value: "customera_name", label: "甲方名称varchar(256)", is_show: true, idx: false,},
    {type: 3, value: "customerb_name", label: "乙方名称varchar(256)", is_show: true, idx: false,},
    {type: 3, value: "customerc_name", label: "丙方名称varchar(256)", is_show: true, idx: false,},
    {type: 3, value: "orga_name", label: "甲方组织机构名称varchar(256)", is_show: true, idx: false,},
    {type: 3, value: "orgb_name", label: "乙方组织机构名称varchar(256)", is_show: true, idx: false,},
    {type: 3, value: "orgc_name", label: "丙方组织机构名称varchar(256)", is_show: true, idx: false,},
    {type: 3, value: "sign_addr", label: "签订地点varchar(256)", is_show: true, idx: false,},
    {type: 3, value: "name", label: "服务名称varchar(256)", is_show: true, idx: false},
    {type: 3, value: "bidding_company", label: "招标单位varchar(256)", is_show: true, idx: false},

    {type: 4, value: "longitude", label: "经度float", is_show: true, idx: false},
    {type: 4, value: "latitude", label: "纬度float", is_show: true, idx: false},
    {type: 4, value: "altitude", label: "海拔float", is_show: true, idx: false},

    {type: 5, value: "contract_price", label: "合同价格numeric(16,4)", is_show: true, idx: false},
    {type: 5, value: "price", label: "限定价格numeric(16,4)", is_show: true, idx: false},
    {type: 5, value: "check_price", label: "验收金额numeric(16,4)", is_show: true, idx: false},
    {type: 5, value: "audit1_price", label: "报审金额numeric(16,4)", is_show: true, idx: false},
    {type: 5, value: "audit2_price", label: "初审金额numeric(16,4)", is_show: true, idx: false},
    {type: 5, value: "audit3_price", label: "终审金额numeric(16,4)", is_show: true, idx: false},
    {type: 5, value: "float_01", label: "numeric(16,4)", is_show: true, idx: true},
    {type: 5, value: "float_02", label: "numeric(16,4)", is_show: true, idx: true},
    {type: 5, value: "float_03", label: "numeric(16,4)", is_show: true, idx: false,},
    {type: 5, value: "float_04", label: "numeric(16,4)", is_show: true, idx: false,},
    {type: 5, value: "float_05", label: "numeric(16,4)", is_show: true, idx: false,},
    {type: 5, value: "float_06", label: "numeric(16,4)", is_show: true, idx: false,},
    {type: 5, value: "float_07", label: "numeric(16,4)", is_show: true, idx: false,},
    {type: 5, value: "float_08", label: "numeric(16,4)", is_show: true, idx: false,},
    {type: 5, value: "float_09", label: "numeric(16,4)", is_show: true, idx: false,},
    {type: 5, value: "float_10", label: "numeric(16,4)", is_show: true, idx: false,},

    {type: 6, value: "sign_time", label: "签订日期date", is_show: true, idx: false},
    {type: 6, value: "start_time", label: "服务开始日期date", is_show: true, idx: false},
    {type: 6, value: "end_time", label: "服务结束日期date", is_show: true, idx: false},
    {type: 6, value: "date_01", label: "date", is_show: true, idx: false},
    {type: 6, value: "date_02", label: "date", is_show: true, idx: false},
    {type: 6, value: "date_03", label: "date", is_show: true, idx: false},
    {type: 6, value: "date_04", label: "date", is_show: true, idx: false},
    {type: 6, value: "date_05", label: "date", is_show: true, idx: false},

    {type: 7, value: "bidding_time", label: "招标时间timestamp with timezone", is_show: true, idx: false},
    {type: 7, value: "check_time", label: "验收时间timestamp with timezone", is_show: true, idx: false},
    {type: 7, value: "audit_time", label: "审计时间timestamp with timezone", is_show: true, idx: false},
    {type: 7, value: "update_time", label: "修改时间timestamp with timezone", is_show: true, idx: false,},
    {type: 7, value: "datetime_01", label: "timestamp with timezone", is_show: true, idx: false},
    {type: 7, value: "datetime_02", label: "timestamp with timezone", is_show: true, idx: false},
    {type: 7, value: "datetime_03", label: "timestamp with timezone", is_show: true, idx: false},
    {type: 7, value: "datetime_04", label: "timestamp with timezone", is_show: true, idx: false},
    {type: 7, value: "datetime_05", label: "timestamp with timezone", is_show: true, idx: false},

    {type: 8, value: "field_01", label: "varchar(1023)", is_show: true, idx: true},
    {type: 8, value: "field_02", label: "varchar(1023)", is_show: true, idx: true},
    {type: 8, value: "field_03", label: "varchar(1023)", is_show: true, idx: true},
    {type: 8, value: "field_04", label: "varchar(1023)", is_show: true, idx: false,},
    {type: 8, value: "field_05", label: "varchar(1023)", is_show: true, idx: false,},
    {type: 8, value: "field_06", label: "varchar(1023)", is_show: true, idx: false,},
    {type: 8, value: "field_07", label: "varchar(1023)", is_show: true, idx: false,},
    {type: 8, value: "field_08", label: "varchar(1023)", is_show: true, idx: false,},
    {type: 8, value: "field_09", label: "varchar(1023)", is_show: true, idx: false,},
    {type: 8, value: "field_10", label: "varchar(1023)", is_show: true, idx: false,},

    {type: 9, value: "int_01", label: "bigint", is_show: true, idx: true},
    {type: 9, value: "int_02", label: "bigint", is_show: true, idx: true},
    {type: 9, value: "int_03", label: "bigint", is_show: true, idx: false},
    {type: 9, value: "int_04", label: "bigint", is_show: true, idx: false},
    {type: 9, value: "int_05", label: "bigint", is_show: true, idx: false},
    {type: 9, value: "int_06", label: "bigint", is_show: true, idx: false},
    {type: 9, value: "int_07", label: "bigint", is_show: true, idx: false},
    {type: 9, value: "int_08", label: "bigint", is_show: true, idx: false},
    {type: 9, value: "int_09", label: "bigint", is_show: true, idx: false},
    {type: 9, value: "int_10", label: "bigint", is_show: true, idx: false},

    {type: 10, value: "text_01", label: "text", is_show: true, idx: false},
    {type: 10, value: "file", label: "附件text", is_show: true, idx: false},
    {type: 10, value: "desc", label: "服务内容text", is_show: true, idx: false},


  ],
};
